[package]
name = "devtool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.19.1"
csv = "1.2.1"
json = "0.12.4"
md-5 = "0.10.5"
simple_excel_writer = "0.2.0"
sqlformat = "0.2.1"
