[package]
name = "devapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fl2rust-macro = "0.5.13"
fltk = "1.4.3"
json = "0.12.4"
devtool = {path = "../devtool"}